FInalizacion ejercicio 2
grondonanicolas/programacion-2-UADE pull request #2
Opened 2023-04-27 19:50 UTC by OrlandoNicolasMarchioli

Genere todas las estructuras abstractas con sus implementaciones genéricas en su forma dinámica, asi como la implementacion del punto 2

2023-04-27 21:47 UTC, nicolas-monzon requested changes
Muy pero muy bien en general, si bien dejo algunas cosas a cambiar, tiene muy buen color este código

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/.idea/.gitignore
Este archivo no debe pushearse. El problema es que ahora que esta pusheado, si agregas la carpeta .idea dentro del `.gitignore`, no te la va a tomar, dado que un archivo pusheado tiene mas prioridad. Tienes que borrar estos archivos de configuración del proyecto (con el IDE cerrado para que no haya problemas), borrar todo excepto src y el pom. Luego, comitteas los archivos borrados como borrados. Luego en el mismo commit o en uno nuevo, subes un `.gitignore` a la altura de la raiz del proyecto donde se ignora todo esto (generate con ChatGPT un `.gitignore` para un proyecto Java, Maven e IntelliJ). Con esto estaría solucionado, sino cada vez que hagas un cambio las configuraciones suelen aparecer como cambios para commitear

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/GenericQueue.java
> +    public GenericQueue() {
Cuando el constructor es vacío no hace falta escribirlo

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/GenericQueue.java
> +        Node node = new Node(a, null);
Aquí usa para declarar el Nodo `Node<T>` y `new Node<>(a, null)`

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/GenericStack.java
> +                +
Me parece raro que esto no rompa, porque hay dos concatenaciones y una esta vacía. Dejá un solo símbolo `+`

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise1/Exercise1.java
>              for (int j = 0; j < specialQueque.getCount(); j++) {
Hago comentario acá porque más abajo no me deja (solo puedo hacer comentarios sobre bloques de código del PR). Más abajo usas un `getArray` para obtener el array interno de Queue. No es lo esperado, porque los TDA encapsulan otras estructuras sin exponerlas, por eso no pusimos este método ni en Stack, Queue, Set, etc. La idea es que pienses un algoritmo que te permita, sin consultar al getArray interno. Propongo algo simple, aunque hay formas mejores, ya que tenes esto andando para el array, crea un método estático `public static int[] toArray(IStack stack)` y un método `public static int[][] toMatrix(SpecialQueue specialQueue)`.

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise1/Exercise1.java
>          for (int i = 0; i < specialQueque.getCount(); i++) {
El getCount() tampoco se debe exponer. Pero, desde fuera te podes abrir un método propio que sea estático y calcule el count sobre esta queue. Tip: tene en cuenta que es una estructura destructiva y necesitas copiarla.

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise2/Exercise2.java
> +    }
El constructor vacío es opcional, podes quitarlo

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise2/Exercise2.java
> +    }
Solo para recordar, la pila original queda destruida. Esto lo considero valido igual porque no estoy evaluando una copia, pero un ámbito real de trabajo hay que tenerlo en cuenta

2023-04-27 21:47 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise2/Exercise2.java
> +        GenericSet setCopied = set;
Esto no copia un conjunto, sino que guarda en una variable su referencia a memoria. Fijate en el repositorio publico que cree en esta cuenta, hay en el package algorithms un método que copia una pila. Debería ser algo análogo a eso pero con conjuntos genéricos

2023-04-28 17:49 UTC, NicolasMarchioli commented on TPO/src/main/java/org/uade/adt/GenericStack.java
> +                +
Si lo pongo asi genera un error, lo genere automaticamente con intellij .

2023-04-28 20:12 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/GenericStack.java
> +                +
Okas, debe ser algo nuevo entonces, confiemos en IntelliJ

2023-04-29 02:09 UTC, NicolasMarchioli commented on TPO/src/main/java/org/uade/exercise1/Exercise1.java
>          for (int i = 0; i < specialQueque.getCount(); i++) {
Una consulta, las copias que intente generar siempre se destruyeron, como se puede generar una copia que no sea volatil ante el remove de la instancia de specialQueue?

2023-04-29 16:31 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise1/Exercise1.java
>          for (int i = 0; i < specialQueque.getCount(); i++) {
Si bien es ineficiente, con lo que se ve en la materia podemos atacar ese problema de la siguiente forma: te creas un metodo estático y público, que recibe lo que queres copiar y devuelve una copia sin modificar la original. Si entras en el repositorio público que tengo en esta cuenta GitHub vas a encontrar un ejemplo con Stack, y lo podes adaptar a cualquier tda que necesites

2023-05-04 18:35 UTC, OrlandoNicolasMarchioli commented on TPO/src/main/java/org/uade/exercise1/Exercise1.java
>          for (int i = 0; i < specialQueque.getCount(); i++) {
Buenas tardes profe.
DIsculpe la demora, estuve varios dias peleando con el codigo y tratando de entender tambien como funcionaban los backups y tambien como implementar el conteo del contenido dentro de las pilas y colas. Genere nuevos metodos y corregi lo que usted menciono anteriormente

2023-05-04 21:12 UTC, nmonzonc3t commented on TPO/src/main/java/org/uade/exercise2/Exercise2.java
> +        GenericSet setCopied = set;
@OrlandoNicolasMarchioli Aun falta esta corrección, de lo contrario no se copiará el conjunto

2023-05-04 21:13 UTC, nmonzonc3t commented on TPO/src/main/java/org/uade/exercise1/Exercise1.java
>          for (int i = 0; i < specialQueque.getCount(); i++) {
No hay problema, avisame cuando tengas todo y hago una segunda review. No debería aparecer nada nuevo pero por las dudas. Consulta, estas solo en el TPO?

2023-05-04 21:53 UTC, OrlandoNicolasMarchioli commented on TPO/src/main/java/org/uade/exercise2/Exercise2.java
> +        GenericSet setCopied = set;
@nmonzonc3t Una pregunta, cuando ejecuto el siguiente codigo, al llegar el ultimo valor, count == 0, pero el nodo del conjunto no es nulo y posee todavia un valor, por lo que al querer elegir el ultimo valor, el metodo choose toma como que no hay mas valores y genera una excepción, para tomar el ultimo valor y salir del bucle, deberia hacer int value=set.getFirst().getValue() y despues setear un nulo en el ultimo nodo?

    public static GenericSet copy(GenericSet<Integer> set) {
        GenericSet<Integer> copy = new GenericSet<>();
        GenericSet<Integer> aux = new GenericSet<>();
        while (!set.isEmpty()) {
            int value = set.choose();
            aux.add(value);
            set.remove(value);
        }
        while (!aux.isEmpty()) {
            int value = aux.choose();
            set.add(value);
            copy.add(value);
            aux.remove(value);
        }
        return copy;
    }

2023-05-05 00:10 UTC, OrlandoNicolasMarchioli commented on TPO/src/main/java/org/uade/exercise1/Exercise1.java
>          for (int i = 0; i < specialQueque.getCount(); i++) {
No no somos 4, los primeros dos puntos los tome yo

2023-05-05 02:59 UTC, nmonzonc3t commented on TPO/src/main/java/org/uade/exercise2/Exercise2.java
> +        GenericSet setCopied = set;
Hola! No me di cuenta que estaba escribiendo desde mi otra cuenta, te pido disculpas. En el repositorio de @nicolas-monzon en los días pasados corregí estos mismos problemas. Fijate como quedó este mismo código corregido. Está todo en el branch `develop`

2023-05-05 03:00 UTC, nmonzonc3t commented on TPO/src/main/java/org/uade/exercise1/Exercise1.java
>          for (int i = 0; i < specialQueque.getCount(); i++) {
Renombra el repositorio siguiendo las convenciones puestas en el archivo TPO. Descárgate la última versión por si quedó desactualizada. Es para saber el número de grupo y así poder trackear esto mientras lo programan

2023-05-05 13:15 UTC, NicolasMarchioli commented on TPO/src/main/java/org/uade/exercise2/Exercise2.java
> +        GenericSet setCopied = set;
Genial, muchas gracias!

2023-05-15 22:19 UTC, merged