Ejercicios 5 y 6
grondonanicolas/programacion-2-UADE pull request #6
Opened 2023-06-21 22:20 UTC by MarianoZalazar

2023-06-23 17:33 UTC, nicolas-monzon requested changes

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/Coord.java
> +public class Coord {
Esta clase en realidad no es una coordenada, es un nodo que contiene x e y. En todo caso, necesitarias una clase Coord que tenga solo atributos x e y, y a su vez, una clase Node que tenga un value de tipo Coord

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/Coord.java
> +    public double get_x(){
Los nombres de los métodos son siempre con camelCase. El snakeCase es la escritura por defecto en Python pero no en Java

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/CoordSet.java
> +        if (this.first.get_x() == x && this.first.get_y() == y) {
Esta doble condicion la podes evitar de acá, si agregas un .equals en la clase Coord. Para eso, podes generarlo con el IDE. Das clic derecho en algún espacio en blanco del archivo y le das clic en Generate -> Overrite methods -> equals

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/CoordSet.java
> +    public int cardinality() {
No hace falta que agregues este método, podes borrarlo

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/DupQueue.java
> +        DequeNode newNode = new DequeNode(a, null, null);
Debajo de esta linea, falta hacer un setNext al nodo de si mismo, y un setPrevious de si mismo

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/DupQueue.java
> +            this.first.setPrevious(null);
Nunca pueden quedar referencias a null, el set es correcto pero tenes que setear el previous con el que era el previous de first antes de la asignación de variable que hiciste al comenzar el bloque de código del else

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/ICoordSet.java
> +    void add(double x, double y);
Si creas la clase Coord como comenté mas arriba, entonces este TDA te queda igual que el que hicimos en clase pero reemplazando int por la clase Coord

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/ICountedSet.java
> +    void remove(int a, int quantity_to_remove);
El comentario de documentación falta para este segundo remove

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/ICountedSet.java
> +    CountedNode choose();
El choose tiene que devolver un número. Esto debe ser de forma aleatoria. Si tenes duplas (valor, total), por ejemplo, (1, 4) entonces decimos que el 1 está 4 veces en el conjunto. Entonces si el conjunto tiene (1, 4) y (2, 3) entonces, tenes que elegir aleatoriamente un valor sobre un arreglo [1, 1, 1, 1, 3, 3, 3]. Si solo tomas aleatoriamente 1 y 2 las probabilidades dan distinto. Entonces, te conviene generar un arreglo, y aplicar el random index que está en el TDA que vimos en clase, con eso mantenes las probabilidades homogeneas

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/ICountedSet.java
> +    void remove(int a);
La documentación no está del todo correcta. Es válida para un conjunto normal. Acá, lo que hace el remove debería ser decrementar en 1 unidad la dupla que contiene como valor al 'a'. Si ese total llega a 0, entonces eliminas la dupla

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/LimitedStack.java
> +            count = 0;
Si guardas el count en un atributo, entonces cada vez que haces un add solo lo tenes que incrementar, y cada vez que eliminas tenes que decrementar. De esta forma, no tenes que recalcular cada vez que se ejecuta, aunque sacrificas unos par de bytes de memoria por el atributo nuevo

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/Montecarlo.java
> +    public Montecarlo(double max_x, double max_y, double min_x, double min_y){
Los nombres de las variables y atributos deben ser con camelCase

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/Montecarlo.java
> +    }
La clase Montecarlo es quien debe tener la logica para calcular pi.
Un truco (aunque en la materia de objetos lo ven formalmente como patrón GRASP -> Experto en información), es preguntar ¿quien tiene la información necesaria para llevar adelante la responsabilidad del calculo?, es esta clase, porque para aproximar pi necesitas las coordenadas y esta clase quien las tiene guardadas

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/normal/IProbGraph.java
> +     * @param weight, peso de la arista.
Ya no tiene este parametro. Aca tenes que decidir si la probabilidad la pedis en este metodo o si pones como descripción de la documentación de este método que la probabilidad la generas en código de forma aleatoria. Tene en cuenta que no puede ser 0 porque es lo mismo que decir que la arista no existe

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise5/Exercise5.java
> +        Stack pila_sin_repetidos = eliminar_repetidos(pila);
Las variables deben ir en camelCase

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/adt/dynamic/Montecarlo.java
> +    private Coord max_coords;
No deberías tener atributos de max y min

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise5/Exercise5.java
> +        double max_coord = 0.23;
Esto no debería estar harcodeado

2023-06-23 17:33 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise5/Exercise5.java
> +            }
La estrategia real para usar montecarlo es la siguiente:
1. Elegis una figura de la que sea facil calcular el area, y que pueda contener la figura de la que deseas averiguar el area
2. Visualmente superpones las figuras, poniendo tu figura dentro de la que conoces el area. Esto en codigo no es necesario. 
3. Bombardeas de puntos aleatorios a ambas figuras, que como estan superpuestas, solo necesitas bombardear a la figura de la que conoces el area.
4. Contas cuandos puntos P_1 cayeron dentro de tu figura, cuantos puntos P_2 bombardeaste a la figura con area conocida, y entonces el area de la figura desconocida es igual a A * P_1 / P_2, siendo A el area de la figura conocida.

Entonces, si elegimos un cuadrado de 1x1, su area es 1. Crear puntos aleatorios para un cuadrado de 1x1 que lo ponemos en el primer cuadrante, es lo mismo que decir que necesitamos generar puntos con `x` entre 0 y 1, con `y` entre 0 y 1. Esto lo podes hacer con Math.random(). Ahora, como el objetivo es encontrar pi, la figura que elijas debería involucrarlo. Un caso sencillo es elegir un círculo, dado que su área es pi*r^2. El circulo que nos conviene no es el que parte del centro del cuadrado, porque la formula para saber si un punto dentro suyo existe, es complicada. El que debemos elegir es el circulo cuyo radio es 1 y esta en el origen de coordenadas. De esta forma, dado un punto del cuadrado si preguntamos si se cumple x^2 + y^2 < 1, entonces si es cierto, ese punto esta dentro del circulo. El tema, es que hay que reajustar la formula porque estamos sobre un cuarto de circulo. Entonces nos queda que, con r = 1, tomando un cuarto de circulo, siendo el area del cuadrado 1:

pi*r^2 /4 = areaCuadrado * puntosDentro/puntosTotales ↔ pi = 4*puntosDentro/puntosTotales. Esto en realidad es una aproximacion, no una igualdad, porque necesitariamos infinitos puntos. Mientras mas grande el numero de puntos aleatorios que generamos, mas cercano a pi será el resultado

2023-06-23 20:36 UTC, MarianoZalazar commented on TPO/src/main/java/org/uade/exercise5/Exercise5.java
> +            }
Hola profe, como va? Ahi realice las correciones de los puntos que me indico, solo me quedaron un par de cuestiones.
1. El tema de devolver un integer para el metodo choose del CountedSet no me convencio, ya que luego no podria obtener cual es la cantidad asignada a ese nodo de ser necesario en algun momento. Es por eso que modifique el codigo utilizando tambien la correcion que me habia hecho sobre la clase Coord (de separarlo para no tener la logica del TDA junto con la logica del nodo en la misma clase) y altere el codigo para que el choose me devuelva un nodo utilizando el concepto de probabilidad homogenea que me corrigio.
2. Sobre el tema de MonteCarlo, creo haberlo corregido como es debido, sumando el tema este de GRASP que menciono. En mi TDA tengo los atributos max y min ya que se habla de definir el cuadrado en el primer cuadrante, es por eso que permito pasarlo como parametro para definir este mismo cuadrado en el TDA. Luego sobre el tema de que no tengo que hardcodear la variable, se refiere a que quiere poder ingresar el valor por consola?
Eso seria todas mis dudas, muchas gracias por su tiempo y correccion

2023-06-24 23:38 UTC, nicolas-monzon commented on TPO/src/main/java/org/uade/exercise5/Exercise5.java
> +            }
Hola Mariano, te comento en respuesta a los items:
1. Con la clase Counted como está ahora me parece que está perfecto
2. Claro. El tema es que si no harcodeas, también sucede que tenes que tener un codigo super generico, y el tp solo exige que aproximes pi. Si usas montecarlo por ejemplo para un subcuadrado dentro de un cuadrado no vas a poder aporximar, pero lo tendrías sin harcodear. Así que creo, que puedo dejarlo pasar. Solo dejá un comentario del por qué elegiste los valores que pusiste para las variables harcodeadas

2023-06-25 21:18 UTC, merged